spring:
  application:
    name: hello
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test-zxyf-mysql.ns-22y35qwz.svc:3306/zxyf?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: jd58xgd5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.hello.entity
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com:
      example:
        hello:
          mapper: debug
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace
